### ISSUE TITLE
Add ability to re-notify folks if they haven't picked up a drink

### ISSUE THREAD

**Issue by robinske** [twilio-labs/twilio-mixologist#18]
Barista requested feature!

**Comment by dkundel** [comment]
These feature requests are all great. We encountered issues like this one before but "re-notifying" people was never something that was requested by our baristas because they were typically too busy to bother. They would just place the orders all to the side and people would either come and pick them up or not. I'm curious if we could find a way that is on the one hand convenient for the baristas and yet doesn't add an additional step (i.e. verifying pick up) for them if they are busy.

**Comment by robinske** [comment]
Agreed - this one might be too much overhead to be worth it, but wanted to record it while I had it on my mind.

**Comment by philnash** [comment]
With #19 you could just add an extra button to completed orders to send a reminder. Baristas would be able to use this when things quiten down during conference sessions if there are still a bunch of coffees (with their numbers) left.

**Comment by IObert** [comment]
Done in the latest version of the project
